torres3000/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from . import views

urlpatterns = [
	path('', views.HomeView.as_view(), name='index'),
	path('apartments/', views.ApartmentsView.as_view(), name='apartments'),
    path('admin/', admin.site.urls),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('cotiza/', views.CotizaView.as_view(), name='cotiza'),
    path('promotora/', views.PromotoraView.as_view(), name='promotora'),
    path('constructora/', views.ConstructoraView.as_view(), name='constructora'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

torres3000/forms.py
# -*- coding: utf-8 -*-
from os.path import basename
from django.utils.translation import ugettext as _
from django import forms
from django.core.exceptions import ValidationError
from torres3000.utils import error_messages

from administration.models import Apartment, Infotype, Cotizacion

class CotizacionForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='CORREO ELECTRÓNICO')
    apartment = forms.ModelChoiceField(queryset=Apartment.objects.filter(deleted=False).all(), label="ESTOY INTERESADO EN", empty_label='ESTOY INTERESADO EN', required=False)
    description = forms.CharField(widget=forms.Textarea, label='MENSAJE')
    info_type = forms.ModelChoiceField(queryset=Infotype.objects.filter(deleted=False).all(),  label="¿CÓMO NOS CONOCISTE?", empty_label='¿CÓMO NOS CONOCISTE?', required=True)

    class Meta:
        model = Cotizacion
        fields = (
            'name',
            'last_name',
            'email',
            'number',
            'description',
            'apartment',
            'info_type',
        )

    def __init__(self, *args, **kwargs):
        super(CotizacionForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].error_messages = error_messages
            self.fields[field].widget.attrs['class'] = ' uk-input'
            self.fields[field].widget.attrs['placeholder'] =  self.fields[field].label

        self.fields['description'].widget.attrs['class'] += ' uk-textarea'
        self.fields['apartment'].widget.attrs['class'] += ' uk-select uk-height-cotiza'
        self.fields['info_type'].widget.attrs['class'] += ' uk-select uk-height-cotiza'
        
        

torres3000/views.py
from django.views.generic import View, FormView, TemplateView, CreateView
from django.utils.translation import ugettext as _
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib import messages

from torres3000.settings import EMAIL_PREFIX, EMAIL_DOMAIN, DEFAULT_FROM_EMAIL, EMAIL_HOST_USER
from django.core.mail import EmailMultiAlternatives
from django.template import loader

from torres3000.forms import CotizacionForm
from administration.models import Cotizacion, Apartment, Infotype


def send_mail(request):
    email_template_name = 'email_cotiza.html'
    apartment_name = ""
    info_name = ""

    if request.POST['apartment']:
        apartment = Apartment.objects.filter(id=request.POST['apartment']).values('name').first()
        apartment_name = apartment['name']

    if request.POST['info_type']:
        info = Infotype.objects.filter(id=request.POST['info_type']).values('name').first()
        info_name = info['name']
    
    context = {
        'domain': "%s%s" % (EMAIL_PREFIX, EMAIL_DOMAIN),  # or your domain
        'site_name': 'Torres3000',
        'protocol': 'http',
        'email':request.POST['email'],
        'first_name':request.POST['name'],
        'last_name':request.POST['last_name'],
        'apartment':apartment_name,
        'info_type':info_name,
        'description':request.POST['description'],
        'number':request.POST['number'],
    }

    from_email = request.POST['email']
    to_email = DEFAULT_FROM_EMAIL

    #from_email = EMAIL_HOST_USER
    #to_email = [request.POST['email'] , 'estefania.heredia@cti.espol.edu.ec']

    html_content = loader.render_to_string(email_template_name, context)
    subject='Torres3000 - Cotización'

    try:
        email_message = EmailMultiAlternatives(subject, html_content, to=to_email, from_email=from_email)   
        email_message.attach_alternative(html_content, "text/html") 
        email_message.mixed_subtype = 'related'

        email_message.send(fail_silently=False)

        return True
    except Exception as e:
        import traceback
        traceback.print_exc()
        print(e)
        return False


class HomeView(CreateView):
    """docstring for HomeView"""
    model = Cotizacion
    template_name = "index.html"

    def send_mail(self): send_mail()

    def form_valid(self, form):
        return super(HomeView, self).form_valid(form)

    def get(self, request, *args, **kwargs):
        data = {
            'title': _(u'Puerto Mocolí'),
            'form': CotizacionForm(),
            'is_cotiza_page' : False,
            }
        return render(request, self.template_name, data)

    def post(self, request, *arg, **kwargs):
        form = CotizacionForm(request.POST)
        data = {}
        data = {'title':  _(u'Puerto Mocolí'),
                'form': form,
                'is_cotiza_page' : False, }

        try:
            if form.is_valid():
                form.save()
                if send_mail(request):
                    messages.success(request, _(u'Se ha enviado correctamente su solicitud.'))
                    return redirect("index")
                else:
                    messages.error(request, _(u'Existe un error al enviar su solicitud.'))
                    return render(request, self.template_name, data)
            else:
                messages.error(request, _(u'Existe al guardar su información.'))
                return render(request, self.template_name, data)
        except Exception as e:
            import traceback;
            traceback.print_exc()
            print(e)
        

class ApartmentsView(CreateView):
    """docstring for ApartmentsView"""
    model = Cotizacion
    template_name = "apartments.html"

    def send_mail(self): send_mail()

    def form_valid(self, form):
        return super(ApartmentsView, self).form_valid(form)

    def get(self, request, *args, **kwargs):
        data = {
            'title': _(u'Departamentos'),
            'form': CotizacionForm(),
            'is_cotiza_page' : False,
            }
        return render(request, self.template_name, data)

    def post(self, request, *arg, **kwargs):
        form = CotizacionForm(request.POST)
        data = {}
        data = {'title': _(u'Departamentos'),
                'form': form,
                'is_cotiza_page' : False, }

        try:
            if form.is_valid():
                form.save()
                if send_mail(request):
                    messages.success(request, _(u'Se ha enviado correctamente su solicitud.'))
                    return redirect("index")
                else:
                    messages.error(request, _(u'Existe un error al enviar su solicitud.'))
                    return render(request, self.template_name, data)
            else:
                messages.error(request, _(u'Existe al guardar su información.'))
                return render(request, self.template_name, data)
        except Exception as e:
            import traceback;
            traceback.print_exc()
            print(e)


class ContactView(TemplateView):
    """docstring for ApartmentsView"""
    template_name = "contact.html"

    def get(self, request):
        return super(ContactView, self).get(request)

    def get_context_data(self, **kwargs):
        context = super(ContactView, self).get_context_data(**kwargs)
        context['title'] = _(u'Contacto')
        return context


class CotizaView(CreateView):
    """docstring for ApartmentsView"""
    model = Cotizacion
    template_name = "cotiza.html"

    def send_mail(self): send_mail()

    def form_valid(self, form):
        return super(CotizaView, self).form_valid(form)

    def get(self, request, *args, **kwargs):
        data = {
            'title': _(u'Cotización'),
            'form': CotizacionForm(),
            'is_cotiza_page' : True,
            }
        return render(request, self.template_name, data)

    def post(self, request, *arg, **kwargs):
        form = CotizacionForm(request.POST)
        data = {}
        data = {'title': _(u'Cotización'),
                'form': form,
                'is_cotiza_page' : False, }

        try:
            if form.is_valid():
                form.save()
                if send_mail(request):
                    messages.success(request, _(u'Se ha enviado correctamente su solicitud.'))
                    return redirect("index")
                else:
                    messages.error(request, _(u'Existe un error al enviar su solicitud.'))
                    return render(request, self.template_name, data)
            else:
                messages.error(request, _(u'Existe al guardar su información.'))
                return render(request, self.template_name, data)
        except Exception as e:
            import traceback;
            traceback.print_exc()
            print(e)


class PromotoraView(TemplateView):
    """docstring for PromotoraView"""
    template_name = "promotora.html"

    def get(self, request):
        return super(PromotoraView, self).get(request)

    def get_context_data(self, **kwargs):
        context = super(PromotoraView, self).get_context_data(**kwargs)
        context['title'] = _(u'Promotora')
        return context


class ConstructoraView(TemplateView):
    """docstring for ConstructoraView"""
    template_name = "constructora.html"

    def get(self, request):
        return super(ConstructoraView, self).get(request)

    def get_context_data(self, **kwargs):
        context = super(ConstructoraView, self).get_context_data(**kwargs)
        context['title'] = _(u'Constructora')
        return context

torres3000/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />

    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="Sr.Blankenbaker">
    <meta name="application-name" content="&nbsp;"/>

    <title>Torres300{% if title %} - {{ title }}{% endif %}</title>

    <meta property="og:title" content="Torres3000"/>
    <meta property="og:type" content="website"/>

    <meta property="og:url" content="https://torres30002.com.ec/"/>
    <meta property="og:site_name" content="Torres30002.com.ec"/>
    <meta property="og:description" content=""/>

    <!-- CSS -->
    <link href="{% static 'uikit/css/uikit.min.css' %}" rel="stylesheet" type="text/css" />

    <!-- FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700" rel="stylesheet" />
    
    <!-- Custom CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    
    {% block extra_head_css %}
    {% endblock %}

    <!-- JS -->
    <script src="{% static 'uikit/js/uikit.min.js' %}"></script>
    <script src="{% static 'uikit/js/uikit-icons.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.1.0.min.js' %}"></script>
    <!--<script src="{% static 'js/functions.js' %}"></script>-->


     <!-- Scripts JS -->
    {% block extra_head_scripts %}
    {% endblock %}

</head>
<body>
    {% include "navbar.html" %}

    {% block title%}
        <div class="uk-section uk-section-muted uk-section-small">
            <div class="uk-container">
                <h4 class="uk-heading-line">{{title}}</h4>
            </div>
        </div>
    {% endblock %}

    {% block banner_container %}
    {% endblock %}

    {% block container %}
    {% endblock %}

    {% if messages %}
        {% for message in messages %}
            <script>
            {% for message in messages %}
                UIkit.notification({message: '{{ message }}', status: '{{ message.tags }}'});

            {% endfor %}
            </script>
        {% endfor %}
    {% endif %}

    {% block footer %}
    <div uk-sticky="sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky">
        <div class="uk-navbar-container">
            <div class="uk-container">
 
                <nav class="uk-navbar-container uk-margin uk-navbar">
                    <div class="uk-navbar-left" style="margin: 0 0 0 10px;">
                        <div>
                            <ul class="uk-navbar-nav">
                                <li><a href="https://www.facebook.com/torres3000ec/" target="_blank" style="padding: 0;"><span class="uk-icon-button uk-margin-small-right" uk-icon="icon: facebook"></span></a></li>
                                <li><a href="https://www.instagram.com/torres3000ec/" target="_blank" style="padding: 0;"><span class="uk-icon-button uk-margin-small-right" uk-icon="icon: instagram"></span></a></li> 
                            </ul>
                        </div>
                    </div>

                    <div class="uk-navbar-right">
                        <div>
                            <ul class="uk-navbar-nav">
                                <li class="uk-width-1"><a href="http://www.mmgtrust.com.ec/" target="_blank" class="uk-navbar-item uk-logo">
                    <img src="{% static 'img/logofootermmg.png' %}" class="uk-square-background-logo-mmg" alt="Torres3000">
                </a></li>
                                <li class="uk-width-1"><a href="http://www.probaquerizo.com/" target="_blank" class="uk-navbar-item uk-logo">
                    <img src="{% static 'img/logofooterprobaquerizo.png' %}" class="uk-square-background-logo-mmg" alt="Torres3000">
                </a></li>
                            </ul>
                        </div>
                    </div>

                </nav>
        </div></div></div>
    {% endblock %}

</body>

</html>

torres3000/templates/constructora.html
{% extends "base.html" %}

{% load static %}
{% block title%}{% endblock %}

{% block container %}

    <div class="uk-card uk-child-width-1-2@s uk-margin-large" style="margin-left: 60px;margin-right: 60px;" uk-grid>
        <div class="uk-card-media-left uk-cover-container" style="padding-left: 0px;">
            <!--<img src="{% static 'img/fotoconstructora.jpg' %}" alt="" uk-cover>
            <canvas width="600" height="600"></canvas>-->
            <div>
        <div class="uk-position-relative uk-visible-toggle" uk-slider="autoplay: true;">
            <ul class="uk-slider-items uk-grid">
                <li class="uk-width-1">
                    <a href="{% url 'cotiza' %}"> <img src="{% static 'img/constructora/fotoconstructora1.jpg' %}" alt=""> </a>
                </li>
                <li class="uk-width-1">
                    <a href="{% url 'cotiza' %}"> <img src="{% static 'img/constructora/fotoconstructora2.jpg' %}" alt=""> </a>
                </li>
                <li class="uk-width-1">
                    <a href="{% url 'cotiza' %}"> <img src="{% static 'img/constructora/fotoconstructora3.jpg' %}" alt=""> </a>
                </li>
                <li class="uk-width-1">
                    <a href="{% url 'cotiza' %}"> <img src="{% static 'img/constructora/fotoconstructora4.jpg' %}" alt=""> </a>
                </li>
                <li class="uk-width-1">
                    <a href="{% url 'cotiza' %}"> <img src="{% static 'img/constructora/fotoconstructora5.jpg' %}" alt=""> </a>
                </li>
                <li class="uk-width-1">
                    <a href="{% url 'cotiza' %}"> <img src="{% static 'img/constructora/fotoconstructora6.jpg' %}" alt=""> </a>
                </li>
            </ul>

            <div class="uk-position-bottom uk-overlay uk-text-center">

            <ul class="uk-slider-nav uk-dotnav uk-flex-center">
            </ul>
            </div>
        </div>
        
    </div>
        </div>
        <div class="uk-padding-remove">
            <div class="uk-card-body uk-padding-remove">
                <div class="uk-div-constructora-head"> <b>CONBAQUERIZO</b> es una compañía constructora, desarrolladora inmobiliaria y de ingenierías con más de 41 años en el mercado. <i>Construye todo tipo de obras civiles a nivel nacional.</i></div>
                
 

                <hr class="uk-border-top-title">
                <p class="uk-description uk-padding-left"><i>Ofreciendo interesantes oportunidades de inversión. </i>.</p>
				<br>
				<p class="uk-description uk-padding-left"><strong>NUESTRA MISIÓN:</strong></p>
                <p class="uk-description uk-padding-left"><i>Conbaquerizo</i>  es una empresa Constructora que brinda servicio y asesoría personalizada tanto a nuestros clientes, como a los que han depositado su confianza en repetidas ocasiones identificándose con nuestras fortalezas como la honestidad, el buen nombre,  la excelente calidad y servicio al cliente, precios competitivos, la entrega a tiempo de las obras, uso de la más avanzada tecnología y gran capacidad de gestión.</p>
				<br>
				<p class="uk-description uk-padding-left"><strong>NUESTRA VISIÓN:</strong></p>
                <p class="uk-description uk-padding-left">Proporcionar a nuestros clientes comodidad, satisfacción, seguridad, y una mejor forma de vida mediante una buena realización de nuestros proyectos, convirtiéndonos en la constructora de confianza de nuestros clientes a través de la buena práctica y la honestidad.</p>
            </div>
        </div>
    </div>

    
{% endblock %}

torres3000/templates/contact.html
{% extends "base.html" %}

{% load static %}
{% block title%}{% endblock %}
{% block banner_container %} {% endblock %}

{% block container %}

<div class="uk-card uk-child-width-1-2@s uk-margin-remove" style="background: #D8D8D8;" uk-grid >
        <div class="uk-flex-last@s uk-card-media-right uk-cover-container">
            <div class="map-responsive">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3987.1399764021644!2d-79.86258646474667!3d-2.0995128705394195!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMsKwMDUnNTguMyJTIDc5wrA1MSc0MC43Ilc!5e0!3m2!1ses!2sec!4v1533560821118" width="600" height="500" frameborder="0" style="border:0" allowfullscreen></iframe>
             </div>
        </div>
        <div class="uk-margin-top">
            <div class="uk-card-body uk-padding-remove-bottom uk-padding uk-width-2-2@s">
                <h3 class="uk-heading uk-text-left">CONTÁCTENOS</h3>
                <hr class="uk-border-top-title">
                <p class="uk-description uk-text-left uk-margin-medium-top uk-margin-small-bottom"><span class="uk-margin-small-right uk-icon" uk-icon="icon: location"></span>Puerto Mocolí 3000</p>

                <p class="uk-description uk-text-left uk-margin-small-bottom"><span class="uk-margin-small-right uk-icon" uk-icon="icon: receiver"></span>+593 99 104 3001</p>

                <p class="uk-description uk-text-left uk-margin-small-bottom"><span class="uk-margin-small-right uk-icon" uk-icon="icon: mail"></span><a href="mailto:info@torres3000.com.ec">info@torres3000.com.ec</a></p>

                <img data-src="{% static 'img/contacto_foto.png' %}" class="uk-margin-medium-top " width="1800" height="1200" alt="" uk-img>
                

                <!--<p class="uk-description uk-text-center"><strong>Dirección de obra:</strong> Km. 6.5 vía a Samborondón, Isla Mocolí, Puerto Mocolí 3000</p>
                <p class="uk-description uk-text-center"><strong>Teléfono:</strong> +593 99 104 3001</p>
                <p class="uk-description uk-text-center"><strong>Email:</strong> <a href="mailto:info@torres3000.com.ec">info@torres3000.com.ec</a></p>-->
            </div>
        </div>
    </div>
    
    
{% endblock %}

torres3000/templates/cotiza.html
{% extends "base.html" %}

{% load static %}
{% block title%}{% endblock %}
{% block banner_container %} {% endblock %}



{% block container %}

        <div class="uk-background-cover uk-height-medium uk-panel uk-flex uk-flex-center uk-flex-middle" style="background-image: url({% static 'img/fondocotiza.jpg' %}); height: 100%;">
            <p class="uk-h4">
			{% include "requireinfo.html" with submit_value="Solicitar información" attr="" form_classes="uk-form-stacked" show_help_texts_in_hidden="True" %}
			</p>
        </div>


{% endblock %}

torres3000/templates/navbar.html
{% load static %}

<div uk-sticky="sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky">
<div class="uk-navbar-container">
    <div class="uk-container">
       
        <nav class="uk-navbar-container uk-margin uk-navbar">
            <div class="uk-navbar-center">
            
                <div class="uk-navbar-center-left uk-nav-menu-banner">
                    <div>
                    <ul class="uk-navbar-nav">
                        <li class="uk-parent ad_navtext_toggle"><a href="{% url 'apartments' %}">DEPARTAMENTOS</a></li>
                        <li class="uk-parent ad_navtext_toggle"><a href="{% url 'constructora' %}">CONSTRUCTORA</a></li>
                    </ul>
                    </div>
                </div>
                
                <a href="{% url 'index' %}" class="uk-navbar-item uk-logo uk-nav-logo-center">
                    <img src="{% static 'img/logo.png' %}" class="uk-responsive-height" alt="Torres3000" style="max-height:150%;">
                </a>

                <div class="uk-navbar-center-right uk-nav-menu-banner">
                    <div>
                        <ul class="uk-navbar-nav">
                            <li class="uk-parent ad_navtext_toggle"><a href="{% url 'promotora' %}">PROMOTORA</a></li>
                            <li class="uk-parent ad_navtext_toggle"><a href="{% url 'cotiza' %}">COTIZA</a></li>
                            <li class="uk-parent ad_navtext_toggle"><a href="{% url 'contact' %}">CONTACTO</a></li>
                        </ul>
                    </div>
                </div>
            </div>

                
            <div class="uk-navbar-left uk-nav-menu-right">
                    <ul class="uk-navbar-nav">
                        <li class="ad_navicon_toggle"><a href="" uk-icon="icon: menu"></a></li>
                        <div uk-dropdown>
                            <ul class="uk-nav uk-dropdown-nav">
                                <li class="uk-nav-header"><a href="{% url 'apartments' %}">DEPARTAMENTOS</a></li>
                                <li class="uk-nav-divider"></li>
                                <li class="uk-nav-header"><a href="{% url 'constructora' %}">CONSTRUCTORA</a></li>
                                <li class="uk-nav-divider"></li>
                                <li class="uk-nav-header"><a href="{% url 'promotora' %}">PROMOTORA</a></li>
                                <li class="uk-nav-divider"></li>
                                <li class="uk-nav-header"><a href="{% url 'cotiza' %}">COTIZA</a></li>
                                <li class="uk-nav-divider"></li>
                                <li class="uk-nav-header"><a href="{% url 'contact' %}">CONTACTO</a></li>
                                <li class="uk-nav-divider"></li>
                            </ul>
                        </div>
                    </ul>
            </div>
               
            <div class="uk-navbar-right">
                <div class="uk-nav-logo-right">
                <a href="{% url 'index' %}" class="uk-navbar-item">
                <img src="{% static 'img/logo.png' %}" class="uk-responsive-height" alt="Torres3000">
                </a>
                </div>

                <div class="uk-nav-menu-right-social">
                    <ul class="uk-navbar-nav">
                        <li><a href="https://www.facebook.com/torres3000ec/" target="_blank" style="padding: 0;"><span class="uk-icon-button uk-margin-small-right" uk-icon="icon: facebook"></span></a></li>
                        <li><a href="https://www.instagram.com/torres3000ec/" target="_blank" style="padding: 0;"><span class="uk-icon-button uk-margin-small-right" uk-icon="icon: instagram"></span></a></li> 
                    </ul>
                </div>

            </div>
            
        </nav>
        </div>
    </div>
</div>

torres3000/templates/requireinfo.html
{% load static %}

<div class="uk-section uk-section-small">
    <div class="uk-container uk-container-small uk-padding-remove">

		{% load staticfiles %}
		{% load widget_tweaks %}

		{% block extra_head_css %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.min.css' %}" />
		{% endblock %}
		{% block extra_head_scripts %}
		<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
		{% endblock %}

        <div class="uk-child-width-1-1@m uk-text-center" uk-grid>
            <div class="uk-padding-remove">
                <div class="uk-card "><h3 class="{% if is_cotiza_page %} uk-description-white-h  {% else %} uk-heading {% endif %}  uk-text-center">SOLICITE INFORMACIÓN</h3></div>
            </div>
            <div class="uk-padding-remove uk-margin-remove-top">
                <div class="uk-card "><hr class=" {% if is_cotiza_page %} uk-divider-small uk-divider-small-white {% else %} uk-divider-small {% endif %} "></div>
            </div>
            <div class="uk-padding-remove uk-margin-remove-top">
                <div class="uk-card "><p class=" {% if is_cotiza_page %} uk-description-white  {% else %} uk-description {% endif %}  uk-padding-left-desc uk-text-center">Por medio del siguiente formulario, escríbanos para solicitar información, recuerde completar todos los campos para un mejor servicios.</p></div>
            </div>
        </div>

        <br><br>

        <form {% if form_id %} id="{{form_id}}" {% endif%} {%if form_classes%} class="{{form_classes}}" {% endif %}  action="" method="POST" {% if form.is_multipart %} enctype="multipart/form-data" {% endif %} {% if form_style %} style="{{ form_style }}" {% endif %} >
        	{% csrf_token %}
        	{{ form.media }}

            {% if form.errors %}
             <ul>
            {% for field in form.visible_fields %}
                {% if field.errors %}
                        <dl class="uk-description-list uk-text-danger">
                        {% for error in field.errors %}
                            <dd class="uk-text-small uk-text-danger">{{ error|escape }}</dd>
                        {% endfor %}
                        </dl>
                                
                {% endif %}                              
            {% endfor %}    
             </ul>                           
            {% endif%}
              

            <div class="uk-child-width-expand@s uk-text-center uk-margin-remove-left  {% if is_cotiza_page %} uk-form-cotiza   {% else %} uk-form-nocotiza  {% endif %}" uk-grid uk-height-match="target: > div > .uk-card">

                <div class="uk-padding-remove-left">
                    <div class="uk-card ">

                	{% for field in form.visible_fields %}
                        {% if field.name == "name" or field.name == "last_name" or field.name == "email" or field.name == "number" or field.name == "apartment" or field.name == "info_type"%}
                       
                            {% if not hide_labels and not field.label == "#hide#" %}
                            
                            {% endif%}
                            <div id="id-{{field.name}}-div" class="uk-form-controls">
                            {% if field.errors %}
                                {{field|add_class:"uk-form-danger"}}
                            </div>

                            {% else %}
                            	{% if is_cotiza_page %}
                                	{{ field|add_class:"uk-inputform-cotiza"}}
                                {% else %}
                                	{{ field|add_class:"uk-inputform-nocotiza"}}
                                {% endif %}
                            </div>
                            {% endif %}
                            {% if show_help_texts %}
                                {{ field.help_text }}
                            {% endif %}
                        
                        {%endif%}   
                    {% endfor %}
                    </div>
                </div>
            
                <div class="uk-padding-remove-left uk-margin-remove-top" >
                    <div class="uk-card ">

                        {% for field in form.visible_fields %}    
                        {% if field.name == "description" %}
                        
                            {% if not hide_labels and not field.label == "#hide#" %}
                               
                            {% endif%}
                            <div id="id-{{field.name}}-div" class="uk-form-controls">
                            {% if field.errors %}
                                <textarea name="description" rows="10" class="uk-input  uk-textarea {% if is_cotiza_page %} uk-inputform-txtcotiza  {% else %} uk-inputform-txtnocotiza {% endif %} uk-form-danger" placeholder="MENSAJE" required="" id="id_description" maxlength="30" cols="40" style="resize: none;margin-top: 0px;margin-bottom: 0px;height: 223px;max-height: 223px;"></textarea>
                            </div>
                            {% else %}
                                <textarea name="description" rows="10" class="uk-input  uk-textarea {% if is_cotiza_page %} uk-inputform-txtcotiza  {% else %} uk-inputform-txtnocotiza {% endif %}" placeholder="MENSAJE" required="" id="id_description" maxlength="30" cols="40" style="resize: none;margin-top: 0px;margin-bottom: 0px;height: 223px;max-height: 223px;"></textarea> 
                            </div>
                            {% endif %}
                            
                            {% if show_help_texts %}
                                {{ field.help_text }}
                            {% endif %}
                        
                        {%endif%}
                        {% endfor %}

                		{% if not noFormActions%}
                	        <div class="form-actions">
                	            <input id="id_1_{{ submit_value }}" class="uk-button   uk-width-1-1  {% if is_cotiza_page %} uk-inputform-btncotiza  {% else %} uk-inputform-btnnocotiza {% endif %} " type="submit" value="{{ submit_value }}" /> 
                	        </div>
                	    {% endif%}
                    </div>
                </div>
            
            </div>
        </form>
    </div>
</div>